/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecrutementRouteImport } from './routes/recrutement'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as JeuRouteImport } from './routes/jeu'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CommanderRouteImport } from './routes/commander'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffLoginRouteImport } from './routes/staff/login'

const RecrutementRoute = RecrutementRouteImport.update({
  id: '/recrutement',
  path: '/recrutement',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const JeuRoute = JeuRouteImport.update({
  id: '/jeu',
  path: '/jeu',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderRoute = CommanderRouteImport.update({
  id: '/commander',
  path: '/commander',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commander': typeof CommanderRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/jeu': typeof JeuRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/recrutement': typeof RecrutementRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commander': typeof CommanderRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/jeu': typeof JeuRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/recrutement': typeof RecrutementRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commander': typeof CommanderRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/jeu': typeof JeuRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/recrutement': typeof RecrutementRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commander'
    | '/confidentialite'
    | '/confirmation'
    | '/contact'
    | '/jeu'
    | '/mentions-legales'
    | '/recrutement'
    | '/staff/login'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commander'
    | '/confidentialite'
    | '/confirmation'
    | '/contact'
    | '/jeu'
    | '/mentions-legales'
    | '/recrutement'
    | '/staff/login'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/commander'
    | '/confidentialite'
    | '/confirmation'
    | '/contact'
    | '/jeu'
    | '/mentions-legales'
    | '/recrutement'
    | '/staff/login'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommanderRoute: typeof CommanderRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ContactRoute: typeof ContactRoute
  JeuRoute: typeof JeuRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  RecrutementRoute: typeof RecrutementRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recrutement': {
      id: '/recrutement'
      path: '/recrutement'
      fullPath: '/recrutement'
      preLoaderRoute: typeof RecrutementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeu': {
      id: '/jeu'
      path: '/jeu'
      fullPath: '/jeu'
      preLoaderRoute: typeof JeuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander': {
      id: '/commander'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommanderRoute: CommanderRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConfirmationRoute: ConfirmationRoute,
  ContactRoute: ContactRoute,
  JeuRoute: JeuRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  RecrutementRoute: RecrutementRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
